# Generated by Django 6.0.3 on 2026-04-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='response',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
